export const POSTS = [
    {
      _id: "1",  // Este id será generado automáticamente por MongoDB
      contenido: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
      fotoPublicacion: "/posts/post1.png",
      usuario:  {
        _id: "usuario_id1",
        nombre: "John Doe",
        fotoPerfil: "/avatars/boy2.png"
      }, // Aquí va el ObjectId del usuario
      comentarios: [
        {
            _id: "comment_id1",
            text: "Nice Tutorial",
            usuario: {
              _id: "usuario_id2",
              nombre: "Jane Doe",
              fotoPerfil: "/avatars/girl1.png"
            }  // ObjectId del usuario que comenta
        }
      ],
      likes: [
        "ObjectId('usuario_id3')",
        "ObjectId('usuario_id4')"
      ]
    },
    {
      _id: "2",
      contenido: "How you guys doing? 😊",
      usuario: {
        _id: "usuario_id1",
        nombre: "John Doe",
        fotoPerfil: "/avatars/boy2.png"
      },
      comentarios: [
        {
          text: "Nice Tutorial",
          usuario: {
            _id: "usuario_id2",
            nombre: "Jane Doe",
            fotoPerfil: "/avatars/girl1.png"
          }
        }
      ],
      likes: [
        "ObjectId('usuario_id3')",
        "ObjectId('usuario_id4')"
      ]
    },
    {
      _id: "3",
      contenido: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
      fotoPublicacion: "/posts/post2.png",
      usuario: {
        _id: "ObjectId('usuario_id3')",
        nombre: "Bob Doe",     
        fotoPerfil: "/avatars/boy3.png"
      },
      comentarios: [],
      likes: [
        "ObjectId('usuario_id3')",
        "ObjectId('usuario_id4')"
      ]
    },
    {
      _id: "4",
      contenido: "I'm learning GO this week. Any tips? 🤔",
      fotoPublicacion: "/posts/post3.png",
      usuario: {
        _id: "ObjectId('usuario_id4')",
        nombre: "Alice Doe",
        fotoPerfil: "/avatars/girl2.png"
      },
      comentarios: [
        {
          text: "Nice Tutorial",
          usuario: {
            _id: "ObjectId('usuario_id4')",
            nombre: "Alice Doe",
            fotoPerfil: "/avatars/girl2.png"
          }
        }
      ],
      likes: [
        "ObjectId('usuario_id3')",
        "ObjectId('usuario_id4')"
      ]
    }
  ];
  
  export const USERS_FOR_RIGHT_PANEL = [
    {
      _id: "ObjectId('usuario_id1')",
      nombre: "John Doe",
      correo: "johndoe@example.com",
      fotoPerfil: "/avatars/boy2.png"
    },
    {
      _id: "ObjectId('usuario_id2')",
      nombre: "Jane Doe",
      correo: "janedoe@example.com",
      fotoPerfil: "/avatars/girl1.png"
    },
    {
      _id: "ObjectId('usuario_id3')",
      nombre: "Bob Doe",
      correo: "bobdoe@example.com",
      fotoPerfil: "/avatars/boy3.png"
    },
    {
      _id: "ObjectId('usuario_id4')",
      nombre: "Daisy Doe",
      correo: "daisydoe@example.com",
      fotoPerfil: "/avatars/girl2.png"
    }
  ];
  